server:
  port: 8888

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: helloModule
          uri: lb://HELLO-SERVICE
          predicates:
            - Path=/api/v2/hello/**
management:
  info:
    git:
      mode: full

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
