server:
  port: 8882

spring:
  application:
    name: hello-service

management:
  info:
    git:
      mode: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
