apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: kubernetes-select-leader
    group: com.ntnn
  name: leader
roleRef:
  apiGroup: ""
  kind: Role
  name: leader
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""