apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader
  labels:
    app: kubernetes-select-leader
    group: com.ntnn
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - watch
      - get
      - update